services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lifesh
    volumes:
      - ./db/postgres/:/var/lib/postgresql/data/
    
  metabase:
    image: metabase/metabase:v0.55.x
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: password
      MB_DB_HOST: postgres
    depends_on:
      - postgres